UnicornStore/Controllers/ShoppingCartController.cs
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using UnicornStore.Models;
using UnicornStore.ViewModels;

namespace UnicornStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly ILogger<ShoppingCartController> _logger;

        public ShoppingCartController(UnicornStoreContext dbContext, ILogger<ShoppingCartController> logger)
        {
            DbContext = dbContext;
            _logger = logger;
        }

        public UnicornStoreContext DbContext { get; }

        //
        // GET: /ShoppingCart/
        public async Task<IActionResult> Index()
        {
            var cart = ShoppingCart.GetCart(DbContext, HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = await cart.GetCartItems(),
                CartTotal = await cart.GetTotal()
            };

            // Return the view
            return View(viewModel);
        }

        //
        // GET: /ShoppingCart/AddToCart/5

        public async Task<IActionResult> AddToCart(int id, CancellationToken requestAborted)
        {
            // Retrieve the blessing from the database
            var addedBlessing = await DbContext.Blessings
                .SingleAsync(blessing => blessing.BlessingId == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(DbContext, HttpContext);

            await cart.AddToCart(addedBlessing);

            await DbContext.SaveChangesAsync(requestAborted);
            _logger.LogInformation("Blessing {blessingId} was added to the cart.", addedBlessing.BlessingId);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveFromCart(
            int id,
            CancellationToken requestAborted)
        {
            // Retrieve the current user's shopping cart
            var cart = ShoppingCart.GetCart(DbContext, HttpContext);

            // Get the name of the blessing to display confirmation
            var cartItem = await DbContext.CartItems
                .Where(item => item.CartItemId == id)
                .Include(c => c.Blessing)
                .SingleOrDefaultAsync();

            string message;
            int itemCount;
            if (cartItem != null)
            {
                // Remove from cart
                itemCount = cart.RemoveFromCart(id);

                await DbContext.SaveChangesAsync(requestAborted);

                string removed = (itemCount > 0) ? " 1 copy of " : string.Empty;
                message = removed + cartItem.Blessing.Title + " has been removed from your shopping cart.";
            }
            else
            {
                itemCount = 0;
                message = "Could not find this item, nothing has been removed from your shopping cart.";
            }

            // Display the confirmation message

            var results = new ShoppingCartRemoveViewModel
            {
                Message = message,
                CartTotal = await cart.GetTotal(),
                CartCount = await cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };

            _logger.LogInformation("Blessing {id} was removed from a cart.", id);

            return Json(results);
        }
    }
}

UnicornStore/Controllers/StoreController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Options;
using UnicornStore.Models;

namespace UnicornStore.Controllers
{
    public class StoreController : Controller
    {
        private readonly AppSettings _appSettings;

        public StoreController(UnicornStoreContext dbContext, IOptionsSnapshot<AppSettings> options)
        {
            DbContext = dbContext;
            _appSettings = options.Value;
        }

        public UnicornStoreContext DbContext { get; }

        //
        // GET: /Store/
        public async Task<IActionResult> Index()
        {
            var genres = await DbContext.Genres.ToListAsync();

            return View(genres);
        }

        //
        // GET: /Store/Browse?genre=Disco
        public async Task<IActionResult> Browse(string genre)
        {
            // Retrieve Genre genre and its Associated associated Blessings blessings from database
            var genreModel = await DbContext.Genres
                .Include(g => g.Blessings)
                .Where(g => g.Name == genre)
                .FirstOrDefaultAsync();

            if (genreModel == null)
            {
                return NotFound();
            }

            return View(genreModel);
        }

        public async Task<IActionResult> Details(
            [FromServices] IMemoryCache cache,
            int id)
        {
            var cacheKey = string.Format("blessing_{0}", id);
            Blessing blessing;
            if (!cache.TryGetValue(cacheKey, out blessing))
            {
                blessing = await DbContext.Blessings
                                .Where(a => a.BlessingId == id)
                                .Include(a => a.Unicorn)
                                .Include(a => a.Genre)
                                .FirstOrDefaultAsync();

                if (blessing != null)
                {
                    if (_appSettings.CacheDbResults)
                    {
                        //Remove it from cache if not retrieved in last 10 minutes
                        cache.Set(
                            cacheKey,
                            blessing,
                            new MemoryCacheEntryOptions().SetSlidingExpiration(TimeSpan.FromMinutes(10)));
                    }
                }
            }

            if (blessing == null)
            {
                return NotFound();
            }

            return View(blessing);
        }
    }
}

UnicornStore/Views/Store/Browse.cshtml
@model Genre
@{
    ViewBag.Title = "Unicorns";
}
<div class="genre">
    <h3>
        <em>@Model.Name</em> Unicorns
    </h3>

    <ul id="blessing-list" class="list-unstyled">
        @foreach (var blessing in Model.Blessings)
        {
            <li class="col-lg-2 col-md-2 col-sm-2 col-xs-4 container">
                <a asp-controller="Store" asp-action="Details" asp-route-id="@blessing.BlessingId">
                    @if (!string.IsNullOrEmpty(blessing.BlessingArtUrl))
                    {
                        <img alt="@blessing.Title" src="@Url.Content(@blessing.BlessingArtUrl)" />
                    }
                    <h5 class="control-label">@blessing.Title</h5>
                </a>
            </li>
        }
    </ul>
</div>

UnicornStore/Views/Store/Details.cshtml
@model Blessing

@{
    ViewBag.Title = "Blessing - " + Model.Title;
}

<h2>@Model.Title</h2>

<p>
    <img alt="@Model.Title" src="@Url.Content(@Model.BlessingArtUrl)" />
</p>

<div id="blessing-details">
    <p>
        <em>Genre:</em>
        @Model.Genre.Name
    </p>
    <p>
        <em>Unicorn:</em>
        @Model.Unicorn.Name
    </p>
    <p>
        <em>Price:</em>
        <label>@Model.Price</label>
    </p>
    <p class="button">
        <a asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-id="@Model.BlessingId">Add to cart</a>
    </p>
</div>

UnicornStore/Views/Store/Index.cshtml
@model IEnumerable<Genre>
@{
    ViewBag.Title = "Store";
}
<h3>Browse Unicorns</h3>

<p>
    Select from @Model.Count() Unicorn genres:
</p>
<ul class="list-group">
    @foreach (var genre in Model)
    {
        <li class="list-group-item"><a asp-controller="Store" asp-action="Browse" asp-route-genre="@genre.Name">@genre.Name</a></li>
    }
</ul>